services:
    mcafee:
        image: mcafee:0.1.3
        ports: 
            - '8000:8000'
    upstream:
        image: node:14.1.0
        ports: 
            - '8080:8080'
        entrypoint: [
                'node',
                '-e',
                "
                require('http').createServer((req, res) => { res.write('test');
                res.end() }).listen(8080);
                "
            ]
    mysql:
        image:  mysql:5.7.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: mcafee

