name: ci

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        run: |
          npm install
          tar -zcf node_modules.zip node_modules/
      - name: upload node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules.zip
          path: node_modules.zip
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/download-artifact@v2
        with:
          name: node_modules.zip
      - name: run test
        run: |
          tar -xf node_modules.zip
          npm run test         
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/download-artifact@v2
        with:
          name: node_modules.zip
      - name: run test
        run: |
          tar -xf node_modules.zip
          npm run build      

        

